from __future__ import annotations

from dataclasses import asdict

from lighting_scene_builder_houdini.core.models import LightingPackage

try:
    import hou  # type: ignore
except ImportError:  # pragma: no cover
    hou = None


def load_lighting_scene(package: LightingPackage) -> dict:
    """Load package into Houdini scene (or simulate in non-Houdini environments)."""
    if hou is None:
        return {
            "mode": "dry_run",
            "message": "hou module unavailable; simulated light scene load",
            "package": asdict(package),
        }

    # Minimal real integration hook for Houdini.
    # Expand this to build object merges, subnetworks, and LOP references as needed.
    root = hou.node("/obj")
    if root is None:
        raise RuntimeError("Houdini /obj root not available")

    subnet = root.createNode("subnet", node_name=f"lightPkg_{package.context.shot}")
    subnet.setComment("Auto-generated by lighting_scene_builder_houdini")
    subnet.moveToGoodPosition()
    return {
        "mode": "houdini",
        "created_node": subnet.path(),
        "compound_count": len(package.compounds),
    }
